import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Outfit } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope", // Custom CSS variable for the font
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit", // Custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "MexSTL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
